alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");
alert("hola mundo");
console.log("pruebas2");

